#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "Do not commit directly to main branch. Please create your own branch and use PR"
  exit 1
fi

if [ "$branch" = "develop" ]; then
  echo "Do not commit directly to develop branch. Please create your own branch and use PR"
  exit 1
fi

tsc
npx lint-staged
